#!/bin/bash

WPM=180  # Words per minute

say -r $WPM -v 'Whisper'   'Hello!'
say -r $WPM -v 'Good News' 'Hello!'
say -r $WPM -v 'Trinoids'  'Hello!'
say -r $WPM -v 'Zarvox'    'Hello!'
say -r $WPM -v 'Wobble'    'Hi!'
say -r $WPM -v 'Boing'     'Hi!'
say -r $WPM -v 'Bubbles'   'Hi!'
say -r $WPM -v 'Albert'    'Hi!'
say -r $WPM -v 'Bahh'      'Hi!'
say -r $WPM -v 'Bells'     'Hello!'
say -r $WPM -v 'Cellos'    'Hello!'
say -r $WPM -v 'Organ'     'Hello!'

say -r $WPM -v 'Majed'     'مرحبًا!'
say -r $WPM -v 'Yelda'     'Merhaba!'
say -r $WPM -v 'Daria'     'Здравей!'
say -r $WPM -v 'Zuzana'    'Dobrý den!'
say -r $WPM -v 'Sara'      'Hej!'
say -r $WPM -v 'Anna'      'Hallo!'
say -r $WPM -v 'Melina'    'Γειά σου!'
say -r $WPM -v 'Mónica'    'Hola!'
say -r $WPM -v 'Montse'    'Hola!'
say -r $WPM -v 'Paulina'   'Hola!'
say -r $WPM -v 'Satu'      'Hei!'
say -r $WPM -v 'Thomas'    'Bonjour!'
say -r $WPM -v 'Amélie'    'Bonjour!'
say -r $WPM -v 'Carmit'    'שלום!'
say -r $WPM -v 'Lekha'     'नमस्कार!'
say -r $WPM -v 'Alice'     'Ciao!'
say -r $WPM -v 'Lana'      'Bog!'
say -r $WPM -v 'Tünde'     'Üdvözlöm!'
say -r $WPM -v 'Damayanti' 'Halo!'
say -r $WPM -v 'Kyoko'     'こんにちは!'
say -r $WPM -v 'Yuna'      '안녕하세요!'
say -r $WPM -v 'Amira'     'Helo!'
say -r $WPM -v 'Nora'      'Hei!'
say -r $WPM -v 'Xander'    'Hallo!'
say -r $WPM -v 'Ellen'     'Hallo!'
say -r $WPM -v 'Zosia'     'Witaj!'
say -r $WPM -v 'Joana'     'Olá!'
say -r $WPM -v 'Luciana'   'Olá!'
say -r $WPM -v 'Ioana'     'Bună!'
say -r $WPM -v 'Milena'    'Здравствуйте!'
say -r $WPM -v 'Lesya'     'Привіт!'
say -r $WPM -v 'Laura'     'Ahoj!'
say -r $WPM -v 'Alva'      'Hej!'
say -r $WPM -v 'Kanya'     'สวัสดีค่ะ!'
say -r $WPM -v 'Linh'      'Xin chào!'
say -r $WPM -v 'Meijia'    '你好!'
say -r $WPM -v 'Tingting'  '你好!'
say -r $WPM -v 'Sinji'     '你好!'

say -r $WPM -v 'Daniel'    'Hello!'
say -r $WPM -v 'Karen'     'Hi!'
say -r $WPM -v 'Moira'     'Hello!'
say -r $WPM -v 'Rishi'     'Hello!'
say -r $WPM -v 'Tessa'     'Hi!'
say -r $WPM -v 'Fred'      'Hello!'
say -r $WPM -v 'Superstar' 'Hi!'
say -r $WPM -v 'Junior'    'Hey-yo!'
say -r $WPM -v 'Kathy'     'Hello!'
say -r $WPM -v 'Ralph'     'Hello!'
say -r $WPM -v 'Samantha'  'Hello!'

read -t 1 ''

say -v 'Bad News'  'Uh oh!'
say -v 'Jester' 'Hello ho ho ho he he he he ha ha ho ha ho ho hu hu he he ho ho hu hu he he ha ha ho ho ho oh oh no oh no no oh no no no'




#echo ''

# echo   'Eddy'
# echo   '            en_US  American English'
# say -v 'Eddy (English (US))'        'Hello! My name is Eddy.'
# echo   '            en_GB  British English'                                                                  
# say -v 'Eddy (English (UK))'        'Hello! My name is Eddy.'
# echo   '            de_DE  German'
# say -v 'Eddy (German (Germany))'    'Hallo! Ich heiße Eddy.'          
# echo   '            fr_FR  Continental French'
# say -v 'Eddy (French (France))'     'Bonjour, je m’appelle Eddy.'
# echo   '            fr_CA  Canadian French'
# say -v 'Eddy (French (Canada))'     'Bonjour, je m’appelle Eddy.'   
# echo   '            es_ES  Continental Spanish'
# say -v 'Eddy (Spanish (Spain))'     '¡Hola! Me llamo Eddy.'     
# echo   '            es_MX  Mexican Spanish'
# say -v 'Eddy (Spanish (Mexico))'    '¡Hola! Me llamo Eddy.'  
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Eddy (Portuguese (Brazil))' 'Olá, meu nome é Eddy.'
# echo   '            it_IT  Italian' 
# say -v 'Eddy (Italian (Italy))'     'Ciao! Mi chiamo Eddy.'          
# echo   '            fi_FI  Finnish'
# say -v 'Eddy (Finnish (Finland))'   'Hei! Nimeni on Eddy.'           

# echo ''

# echo   'Flo'
# echo   '            en_US  American English'
# say -v 'Flo (English (US))'            'Hello! My name is Flo.'
# echo   '            en_GB  British English'
# say -v 'Flo (English (UK))'            'Hello! My name is Flo.' 
# echo   '            de_DE  German'
# say -v 'Flo (German (Germany))'        'Hallo! Ich heiße Flo.'           
# echo   '            fr_FR  Continental French'
# say -v 'Flo (French (France))'         'Bonjour, je m’appelle Flo.' 
# echo   '            fr_CA  Canadian French'
# say -v 'Flo (French (Canada))'         'Bonjour, je m’appelle Flo.'    
# echo   '            es_ES  Continental Spanish'
# say -v 'Flo (Spanish (Spain))'         '¡Hola! Me llamo Flo.'      
# echo   '            es_MX  Mexican Spanish'
# say -v 'Flo (Spanish (Mexico))'        '¡Hola! Me llamo Flo.'   
# echo   '            pt_BR  Brazilian Portugese'
# say -v 'Flo (Portuguese (Brazil))'     'Olá, meu nome é Flo.'     
# echo   '            it_IT  Italian'
# say -v 'Flo (Italian (Italy))'         'Ciao! Mi chiamo Flo.'           
# echo   '            fi_FI  Finnish'
# say -v 'Flo (Finnish (Finland))'       'Hei! Nimeni on Flo.'         

# echo ''

# echo   'Grandma'
# echo   '            en_US  American English'
# say -v 'Grandma (English (US))'        'Hello! Please call me Grandma.'
# echo   '            en_GB  British English'
# say -v 'Grandma (English (UK))'        'Hello! Please call me Grandma.' 
# echo   '            de_DE  German'
# say -v 'Grandma (German (Germany))'    'Hallo! Ich heiße Grandma.'       
# echo   '            fr_FR  Continental French'
# say -v 'Grandma (French (France))'     'Bonjour, je m’appelle Grandma.'
# echo   '            fr_CA  Canadian French'
# say -v 'Grandma (French (Canada))'     'Bonjour, je m’appelle Grandma.'
# echo   '            es_ES  Continental Spanish'
# say -v 'Grandma (Spanish (Spain))'     '¡Hola! Me llamo Grandma.'  
# echo   '            es_MX  Mexican Spanish'
# say -v 'Grandma (Spanish (Mexico))'    '¡Hola! Me llamo Grandma.'      
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Grandma (Portuguese (Brazil))' 'Olá, meu nome é Grandma.' 
# echo   '            it_IT  Italian'
# say -v 'Grandma (Italian (Italy))'     'Ciao! Mi chiamo Grandma.'   
# echo   '            fi_FI  Finnish'
# say -v 'Grandma (Finnish (Finland))'   'Hei! Nimeni on Grandma.'        

# echo ''

# echo   'Grandpa'
# echo   '            en_US  American English'
# say -v 'Grandpa (English (US))'        'Hello! Please call me Grandpa.'
# echo   '            en_GB  British English'
# say -v 'Grandpa (English (UK))'        'Hello! Please call me Grandpa.'  
# echo   '            de_DE  German'
# say -v 'Grandpa (German (Germany))'    'Hallo! Ich heiße Grandpa.'       
# echo   '            fr_FR  Continental French'
# say -v 'Grandpa (French (France))'     'Bonjour, je m’appelle Grandpa.'
# echo   '            fr_CA  Canadian French'
# say -v 'Grandpa (French (Canada))'     'Bonjour, je m’appelle Grandpa.'   
# echo   '            es_ES  Continental Spanish'
# say -v 'Grandpa (Spanish (Spain))'     '¡Hola! Me llamo Grandpa.'  
# echo   '            es_MX  Mexican Spanish'
# say -v 'Grandpa (Spanish (Mexico))'    '¡Hola! Me llamo Grandpa.'      
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Grandpa (Portuguese (Brazil))' 'Olá, meu nome é Grandpa.' 
# echo   '            it_IT  Italian'
# say -v 'Grandpa (Italian (Italy))'     'Ciao! Mi chiamo Grandpa.'   
# echo   '            fi_FI  Finnish'
# say -v 'Grandpa (Finnish (Finland))'   'Hei! Nimeni on Grandpa.'        

# echo ''

# echo   'Reed'
# echo   '            en_US  American English'
# say -v 'Reed (English (US))'           'Hello! My name is Reed.'    
# echo   '            en_GB  British English'
# say -v 'Reed (English (UK))'           'Hello! My name is Reed.'
# echo   '            de_DE  German'
# say -v 'Reed (German (Germany))'       'Hallo! Ich heiße Reed.'          
# echo   '            fr_CA  Canadian French'
# say -v 'Reed (French (Canada))'        'Bonjour, je m’appelle Reed.'   
# echo   '            es_ES  Continental Spanish'
# say -v 'Reed (Spanish (Spain))'        '¡Hola! Me llamo Reed.'     
# echo   '            es_MX  Mexican Spanish'
# say -v 'Reed (Spanish (Mexico))'       '¡Hola! Me llamo Reed.'  
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Reed (Portuguese (Brazil))'    'Olá, meu nome é Reed.'    
# echo   '            it_IT  Italian'
# say -v 'Reed (Italian (Italy))'        'Ciao! Mi chiamo Reed.'          
# echo   '            fi_FI  Finnish'
# say -v 'Reed (Finnish (Finland))'      'Hei! Nimeni on Reed.'       

# echo ''

# echo   'Rocko'
# echo   '            en_US  American English'
# say -v 'Rocko (English (US))'          'Hello! My name is Rocko.'   
# echo   '            en_GB  British English'
# say -v 'Rocko (English (UK))'          'Hello! My name is Rocko.'      
# echo   '            de_DE  German'
# say -v 'Rocko (German (Germany))'      'Hallo! Ich heiße Rocko.'         
# echo   '            fr_FR  Continental French'
# say -v 'Rocko (French (France))'       'Bonjour, je m’appelle Rocko.'  
# echo   '            fr_CA  Canadian French'
# say -v 'Rocko (French (Canada))'       'Bonjour, je m’appelle Rocko.'  
# echo   '            es_MX  es_ES  Continental Spanish'
# say -v 'Rocko (Spanish (Spain))'       '¡Hola! Me llamo Rocko.'    
# echo   '            Mexican Spanish'
# say -v 'Rocko (Spanish (Mexico))'      '¡Hola! Me llamo Rocko.' 
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Rocko (Portuguese (Brazil))'   'Olá, meu nome é Rocko.'   
# echo   '            it_IT  Italian'
# say -v 'Rocko (Italian (Italy))'       'Ciao! Mi chiamo Rocko.'         
# echo   '            fi_FI  Finnish'
# say -v 'Rocko (Finnish (Finland))'     'Hei! Nimeni on Rocko).'      

# echo ''

# echo   'Sandy'
# echo   '            en_US  American English'
# say -v 'Sandy (English (US))'          'Hello! My name is Sandy.'  
# echo   '            en_GB  British English'
# say -v 'Sandy (English (UK))'          'Hello! My name is Sandy.'      
# echo   '            de_DE  German'
# say -v 'Sandy (German (Germany))'      'Hallo! Ich heiße Sandy.'         
# echo   '            fr_FR  Continental French'
# say -v 'Sandy (French (France))'       'Bonjour, je m’appelle Sandy.'  
# echo   '            fr_CA  Canadian French'
# say -v 'Sandy (French (Canada))'       'Bonjour, je m’appelle Sandy.'  
# echo   '            es_ES  Continental Spanish'
# say -v 'Sandy (Spanish (Spain))'       '¡Hola! Me llamo Sandy.'    
# echo   '            es_MX  Mexican Spanish'
# say -v 'Sandy (Spanish (Mexico))'      '¡Hola! Me llamo Sandy.' 
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Sandy (Portuguese (Brazil))'   'Olá, meu nome é Sandy.'  
# echo   '            it_IT  Italian'
# say -v 'Sandy (Italian (Italy))'       'Ciao! Mi chiamo Sandy.'         
# echo   '            fi_FI  Finnish'
# say -v 'Sandy (Finnish (Finland))'     'Hei! Nimeni on Sandy.'          

# echo ''

# echo   'Shelley'
# echo   '            en_US  American English'
# say -v 'Shelley (English (US))'        'Hello! My name is Shelley.' 
# echo   '            en_GB  British English'
# say -v 'Shelley (English (UK))'        'Hello! My name is Shelley.'    
# echo   '            de_DE  German'
# say -v 'Shelley (German (Germany))'    'Hallo! Ich heiße Shelley.'       
# echo   '            fr_FR  Continental French'
# say -v 'Shelley (French (France))'     'Bonjour, je m’appelle Shelley.'
# echo   '            fr_CA  Canadian French'
# say -v 'Shelley (French (Canada))'     'Bonjour, je m’appelle Shelley.'
# echo   '            es_ES  Continental Spanish'
# say -v 'Shelley (Spanish (Spain))'     '¡Hola! Me llamo Shelley.'  
# echo   '            es_MX  Mexican Spanish'
# say -v 'Shelley (Spanish (Mexico))'    '¡Hola! Me llamo Shelley.'      
# echo   '            pt_BR  Brazilian Portuguese'
# say -v 'Shelley (Portuguese (Brazil))' 'Olá, meu nome é Shelley.'    
# echo   '            it_IT  Italian'
# say -v 'Shelley (Italian (Italy))'     'Ciao! Mi chiamo Shelley.'   
# echo   '            fi_FI  Finnish'
# say -v 'Shelley (Finnish (Finland))'   'Hei! Nimeni on Shelley.'        

echo ''

# echo   'Majed       ar_001 Modern Standard Arabic'
# say -v 'Majed'     'مرحبًا، اسمي ماجد. أنا صوتٌ عربي.'

# echo   'Yelda       tr_TR  Turkish'
# say -v 'Yelda'     'Merhaba, benim adım Yelda. Ben Türkçe bir sesim.'

# echo   'Daria       bg_BG  Bulgarian'
# say -v 'Daria'     'Здравей, казвам се Дария и съм български глас.'

# echo   'Zuzana      cs_CZ  Czech'
# say -v 'Zuzana'    'Dobrý den, jmenuji se Zuzana. Jsem český hlas.'

# echo   'Sara        da_DK  Danish'
# say -v 'Sara'      'Hej, jeg hedder Sara. Jeg er en dansk stemme.'

# echo   'Anna        de_DE  German'
# say -v 'Anna'      'Hallo, ich heiße Anna und ich bin eine deutsche Stimme.'

# echo   'Melina      el_GR  Modern Greek'
# say -v 'Melina'    'ονομάζομαι Μελίνα. Μιλάω ελληνικά.'

# echo   'Mónica      es_ES  Continental Spanish'
# say -v 'Mónica'    'Hola, me llamo Mónica y soy una voz española.'

# echo   'Montse      ca_ES  Catalan'
# say -v 'Montse'    'Hola, em dic Montse i soc una veu catalana.'

# echo   'Paulina     es_MX  Mexican Spanish'
# say -v 'Paulina'   'Hola, me llamo Paulina y soy una voz mexicana.'

# echo   'Satu        fi_FI  Finnish'
# say -v 'Satu'      'Hei, minun nimeni on Satu. Olen suomalainen ääni.'

# echo   'Jacques     fr_FR  Continental French'
# say -v 'Jacques'   'Bonjour, je m’appelle Jacques. Je suis une voix française.'

# echo   'Thomas      fr_FR  Continental French'
# say -v 'Thomas'    'Bonjour, je m’appelle Thomas. Je suis une voix française.'

# echo   'Amélie      fr_CA  Canadian French'
# say -v 'Amélie'    'Bonjour, je m’appelle Amélie. Ma voix est en français canadien.'

# echo   'Carmit      he_IL  Hebrew'
# say -v 'Carmit'    'שלום. קוראים לי כרמית, ואני קול בשפה העברית.'

# echo   'Lekha       hi_IN  Hindi'
# say -v 'Lekha'     'नमस्कार, मेरा नाम लेखा है! मैं हिन्दी में बोलने वाली आवाज़ हूँ!'

# echo   'Alice       it_IT  Italian' 
# say -v 'Alice'     'Salve, mi chiamo Alice e sono una voce italiana.'

# echo   'Lana        hr_HR  Croatian'
# say -v 'Lana'      'Bog! Moje je ime Lana. Ja sam hrvatski glas.'

# echo   'Tünde       hu_HU  Hungarian'
# say -v 'Tünde'     'Üdvözlöm! Tünde vagyok. Én vagyok a magyar hang.'

# echo   'Damayanti   id_ID  Indonesian'
# say -v 'Damayanti' 'Halo, nama saya Damayanti. Saya berbahasa Indonesia.'

# echo   'Kyoko       ja_JP  Japanese'
# say -v 'Kyoko'     'こんにちは、私の名前はきょうこです。日本語の音声をお届けします。'

# echo   'Yuna        ko_KR  South Korean'
# say -v 'Yuna'      '안녕하세요. 제 이름은 유나입니다. 저는 한국어 음성입니다.'

# echo   'Amira       ms_MY  Malay'
# say -v 'Amira'     'Helo, nama saya Amira. Saya bercakap Bahasa Melayu.'

# echo   'Nora        nb_NO  Norwegian Bokmål'
# say -v 'Nora'      'Hei, jeg heter Nora. Jeg er en norsk stemme.'

# echo   'Xander      nl_NL  Netherlands Dutch'
# say -v 'Xander'    'Hallo, mijn naam is Xander. Ik ben een Nederlandse stem.'

# echo   'Ellen       nl_BE  Belgian Dutch'
# say -v 'Ellen'     'Hallo, mijn naam is Ellen. Ik ben een Belgisch-Nederlandse stem.'

# echo   'Zosia       pl_PL  Polish'
# say -v 'Zosia'     'Witaj. Mam na imię Zosia, jestem głosem kobiecym dla języka polskiego.'

# echo   'Joana       pt_PT  Continental Portugese'
# say -v 'Joana'     'Olá, chamo-me Joana e dou voz ao português falado em Portugal.'

# echo   'Luciana     pt_BR  Brazilian Portugese'
# say -v 'Luciana'   'Olá, o meu nome é Luciana e a minha voz corresponde ao português que é falado no Brasil'

# echo   'Ioana       ro_RO  Romanian'
# say -v 'Ioana'     'Bună, mă cheamă Ioana. Sunt o voce românească.'

# echo   'Milena      ru_RU  Russian'
# say -v 'Milena'    'Здравствуйте, меня зовут Милена. Я — русский голос системы.'

# echo   'Lesya       uk_UA  Ukranian'
# say -v 'Lesya'     'Привіт, мене звуть Леся. Я — український голос.'

# echo   'Laura       sk_SK  Slovak'
# say -v 'Laura'     'Ahoj. Volám sa Laura. Som hlas v slovenskom jazyku.'

# echo   'Alva        sv_SE  Swedish'
# say -v 'Alva'      'Hej, jag heter Alva. Jag är en svensk röst.'

# echo   'Kanya       th_TH  Thai'
# say -v 'Kanya'     'สวัสดีค่ะ ดิฉันชื่อกันยา'

# echo   'Linh        vi_VN  Vietnamese'
# say -v 'Linh'      'Xin chào, tên tôi là Linh. Tôi là giọng nói Tiếng Việt.'

# echo   'Meijia      zh_TW  Literary Chinese'
# say -v 'Meijia'    '你好，我叫美佳。我說國語。'

# echo   'Tingting    zh_CN  Mainland Chinese Mandarin'
# say -v 'Tingting'  '你好，我叫 婷婷。我是中文普通话语音。'

# echo   'Sinji       zh_HK  Hong Kong Cantonese'
# say -v 'Sinji'     '你好，我叫善怡。我講廣東waa2。'


# echo ''

# echo   'Daniel      en_GB  British English'
# say -v 'Daniel'    'Hello! My name is Daniel. I sure like being inside this fancy computer.'

# echo   'Karen       en_AU  Australian English'
# say -v 'Karen'     'Hello! My name is Karen. I sure like being inside this fancy computer.'

# echo   'Moira       en_IE  Irish English'
# say -v 'Moira'     'Hello! My name is Moira.  I sure like being inside this fancy computer.'

# echo   'Rishi       en_IN  Indian English'
# say -v 'Rishi'     'Hello! My name is Rishi. I sure like being inside this fancy computer.'

# echo   'Tessa       en_ZA  South African English'
# say -v 'Tessa'     'Hello! My name is Tessa. I sure like being inside this fancy computer.'


# echo   'Fred        en_US  American English'
# say -v 'Fred'      'Hello! My name is Fred.'

# echo   'Junior      en_US  American English'
# say -v 'Junior'    'Hello! My name is Junior. My favorite food is pizza.'

# echo   'Kathy       en_US  American English'
# say -v 'Kathy'     'Hello! My name is Kathy.'

# echo   'Ralph       en_US  American English'
# say -v 'Ralph'     'Hello! My name is Ralph. The sum of the squares of the legs of a right triangle is equal to the square of the hypotenuse.'

# echo   'Samantha    en_US  American English'
# say -v 'Samantha'  'Hello! My name is Samantha.'

# echo   'Superstar   en_US  American English'
# say -v 'Superstar' 'Hello! My name is Superstar. When I grow up I’m going to be a scientist.'

# echo ''

# echo   'Bad News   '
# say -v 'Bad News'  'Hello! My name is Bad News.'
# echo   'Good News  '
# say -v 'Good News' 'Hello! My name is Good News.'

# echo   'Albert      "I have a frog in my throat. No, I mean a real frog!"'                                   
# say -v 'Albert'    'Hello! My name is Albert. I have a frog in my throat. No, I mean a real frog!'
# echo   'Bahh        "Do not pull the wool over my eyes."'
# say -v 'Bahh'      'Hello! My name is Bahh. Do not pull the wool over my eyes.'
# echo   'Boing       "Spring has sprung, fall has fell, winter's here and it's colder than usual."'
# say -v 'Boing'     'Hello! My name is Boing. Spring has sprung, fall has fell, winter's here and it's colder than usual.'
# echo   'Bubbles    '
# say -v 'Bubbles'   'Hello! My name is Bubbles.'
# echo   'Wobble     '
# say -v 'Wobble'    'Hello! My name is Wobble.'
# echo   'Jester      "Please stop tickling me!"'
# say -v 'Jester'    'Hello! My name is Jester. Please stop tickling me!'

# echo   'Bells       "Time flies when you are having fun."'
# say -v 'Bells'     'Hello! My name is Bells. Time flies when you are having fun.'
# echo   'Cellos      "Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo."'
# say -v 'Cellos'    'Hello! My name is Cellos. Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo.'
# echo   'Organ       "We must rejoice in this morbid voice."'
# say -v 'Organ'     'Hello! My name is Organ. We must rejoice in this morbid voice.'

# echo   'Trinoids    "We cannot communicate with these carbon units."'
# say -v 'Trinoids'  'Hello! My name is Trinoids. We cannot communicate with these carbon units.'
# echo   'Whisper     "Pssssst, hey you, Yeah you, Who do ya think I’m talking to, the mouse?"'
# say -v 'Whisper'   'Hello! My name is Whisper. Pssssst, hey you, Yeah you, Who do ya think I’m talking to, the mouse?'
# echo   'Zarvox      "That looks like a peaceful planet."'
# say -v 'Zarvox'    'Hello! My name is Zarvox. That looks like a peaceful planet.'
